### ISSUE TITLE
update mouse usage

### ISSUE THREAD

**Issue by hainm** [arose/ngl#364]
As I mention in email, I think NGL docs should add a section about mouse usage (e.g from http://nglviewer.org/ngl/): mouse + trackpad

**Comment by arose** [comment]
done, see 78ed204336e0b98fa4c5f0775f86dcbc335ca0b7

**Comment by hainm** [comment]
thanks.

**Comment by hainm** [comment]
I think still missing

- translate
- pickling: How can I do that on mac trackpad?

**Comment by arose** [comment]
pan is translate, clarified that, also added zoom on clickPick-shift-left, see a631b3e62342e05bfc2c75c19173641bcc4cdd04
