### ISSUE TITLE
loading pdb

### ISSUE THREAD

**Issue by drc007** [arose/ngl#647]
I'm trying the demo in the gallery the "interactive/ligand-viewer" and I'm finding that some pdb files load fine but some fail with an error 

[Error] Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'rp.entity.description')
	(anonymous function) (index.html:249)
	eachResidue (ngl.js:1:896076)
	(anonymous function) (ngl.js:1:899067)
	eachChain (ngl.js:1:899453)
	eachResidue (ngl.js:1:899041)
	eachResidue (ngl.js:1:904851)
	setLigandOptions (index.html:242)
	(anonymous function) (index.html:174)
	promiseReactionJob

I'm guessing there must be some particular feature in the pdb file that is missing, they open fine in MOE.

I've attached an example of the problematic files.
[349_2_refmac2.pdb.zip](https://github.com/arose/ngl/files/3117108/349_2_refmac2.pdb.zip)

**Comment by fredludlow** [comment]
The code is expecting the structure to have an 'entity' attribute but it's missing if the input PDB doesn't have a CMPND record, should be fixed in #648.

**Comment by drc007** [comment]
Thanks

**Comment by drc007** [comment]
I'm afraid I still get a similar error.

[Error] Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'rp.entity.description')
	(anonymous function) (index.html:250)
	eachResidue (ngl.js:1:909540)
	(anonymous function) (ngl.js:1:912531)
	eachChain (ngl.js:1:912917)
	eachResidue (ngl.js:1:912505)
	eachResidue (ngl.js:1:918315)
	setLigandOptions (index.html:243)
	(anonymous function) (index.html:175)
	promiseReactionJob

**Comment by drc007** [comment]
I'm afraid I still get a similar error.

[Error] Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'rp.entity.description')
(anonymous function) (index.html:250)
eachResidue (ngl.js:1:909540)
(anonymous function) (ngl.js:1:912531)
eachChain (ngl.js:1:912917)
eachResidue (ngl.js:1:912505)
eachResidue (ngl.js:1:918315)
setLigandOptions (index.html:243)
(anonymous function) (index.html:175)
promiseReactionJob

**Comment by arose** [comment]
Hey @drc007, the fix was not released yet, just done in the code.

I pushed it now, please try again and make sure the version number displayed is "2.0.0-dev.36"

**Comment by drc007** [comment]
Hi,

Apologies I’m new to this.

I did 

npm install ngl@next

+ ngl@2.0.0-dev.36

I then replaced the ngl.js on my web server for the new version I just downloaded,

Still get the error though

So tried downloading

https://github.com/arose/ngl/releases/tag/v2.0.0-dev.36 <https://github.com/arose/ngl/releases/tag/v2.0.0-dev.36>

And tried using the ngl.js for the dist folder.

Still get the same error.

**Comment by fredludlow** [comment]
The change was to the example script, not ngl.js: 
Can you check your version of 
examples/scripts/interactive/ligand-viewer.js
has the changes shown here:
https://github.com/arose/ngl/pull/648/files

I've just updated a previous checkout by doing:
```bash
git pull
npm install
npm build
```
And now it seems to be working for the file you originally attached.
You can test it here:
https://fredludlow.com/ngl/upstream/examples/webapp.html?script=interactive/ligand-viewer

**Comment by drc007** [comment]
OK, I understand now.
